# Generated by Django 5.2.11 on 2026-02-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('annual_fee', models.PositiveIntegerField(default=0)),
                ('fee_waiver_spend', models.PositiveIntegerField(default=0, help_text='Annual spend required to waive fee')),
                ('lounge_visits_per_year', models.PositiveIntegerField(default=0)),
                ('forex_markup_percent', models.FloatField(default=0.0, help_text='Forex markup percentage')),
                ('min_income_required', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('online', 'Online'), ('fuel', 'Fuel'), ('dining', 'Dining'), ('travel', 'Travel'), ('groceries', 'Groceries'), ('other', 'Other')], max_length=20)),
                ('reward_rate', models.FloatField(help_text='Cashback or value rate (e.g., 0.05 for 5%)')),
                ('monthly_cap', models.PositiveIntegerField(blank=True, help_text='Maximum spend eligible for rewards per month', null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='core.creditcard')),
            ],
        ),
    ]
