# Generated by Django 5.2.11 on 2026-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardcategory',
            name='monthly_cap',
        ),
        migrations.AddField(
            model_name='rewardcategory',
            name='cap_type',
            field=models.CharField(choices=[('none', 'No Cap'), ('spend', 'Spend Cap'), ('cashback', 'Cashback Cap')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='rewardcategory',
            name='monthly_cap_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Cap value: spend or cashback depending on cap_type', null=True),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='reward_rate',
            field=models.FloatField(help_text='Cashback rate (e.g., 0.05 for 5%)'),
        ),
    ]
