# Generated by Django 5.2.11 on 2026-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_rewardcategory_monthly_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='supports_forex',
            field=models.BooleanField(default=True, help_text='Whether the card supports international transactions'),
        ),
    ]
